version: '3.8'
services:
  api:
    container_name: 'maap-api-nasa'
    image: 'maap-api-nasa'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/maap-api-nasa/logs/
    command: >
      sh -c "gunicorn --bind 0.0.0.0:5000 api.maapapp:app -w 4"
    environment:
      FLASK_APP: /maap-api-nasa/api/maapapp.py
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 250m
        max-file: 10
      retries: 50
