version: '3.8'
services:
  api:
    container_name: 'maap-api-nasa'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    ports:
      - "5000:5000"
    command: >
      sh -c "flask run --host=0.0.0.0"
    environment:
      FLASK_APP: /maap-api-nasa/api/maapapp.py
    restart: always

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: maap
      POSTGRES_USER: maapuser
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresql://maapuser:mysecretpassword@db/maap"]
      interval: 5s
      timeout: 5s
      retries: 50
